# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: "2.4"

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
  mysql:
    build:
      context: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - ../:/var/www
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - INSTALL_GRPC:${PHP_FPM_INSTALL_GRPC}
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ../:/var/www

volumes:
  mysql:
    driver: local
