# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: "2.4"

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
  mysql:
    build:
      context: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
