version: "2.4"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  nginx:
    driver: ${VOLUMES_DRIVER}

services:
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    networks:
      - backend
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    depends_on:
      - php-fpm
    networks:
      - backend
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${APP_CODE_PATH_HOST}:/var/www
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - INSTALL_GRPC:${PHP_FPM_INSTALL_GRPC}
        - VERSION=${PHP_FPM_VERSION}
    expose:
      - "9000"
    networks:
      - backend
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:/var/www
